# Generated by Django 3.2.8 on 2021-10-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_alter_departamento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='usuario',
        ),
    ]
